No need for KinD cluster when running RIAB (#454)

diff --git a/build/bin/smoke-riab b/build/bin/smoke-riab
--- a/build/bin/smoke-riab
+++ b/build/bin/smoke-riab
@@ -29,7 +29,22 @@ WORKSPACE=${WORKSPACE:-~}
 export SDRAN_USERNAME=$repo_user
 export SDRAN_PASSWORD=$repo_password
 
-# directory to hold the dowloaded charts
+# clone the RIAB sources
+rm -rf riab-workspace && mkdir riab-workspace
+pushd riab-workspace
+git clone git@github.com:onosproject/sdran-in-a-box.git
+
+# clean up from any previous runs
+cd sdran-in-a-box
+make clean-all
+
+# in case there is a left over KinD cluster, delete it
+kind delete cluster
+
+# Force images to be downloaded
+docker rmi --force $(docker images -a -q) || true
+
+# directory to hold the downloaded charts
 rm -rf ${WORKSPACE}/helm-charts
 mkdir ${WORKSPACE}/helm-charts
 pushd ${WORKSPACE}/helm-charts
@@ -37,25 +52,12 @@ pushd ${WORKSPACE}/helm-charts
 # pull down the chart repos
 
 # aether charts
-git clone ssh://jenkins@gerrit.opencord.org:29418/aether-helm-charts
+git clone ssh://ray@gerrit.opencord.org:29418/aether-helm-charts
 
 # onos sdran charts
 git clone git@github.com:onosproject/sdran-helm-charts.git
 
 popd
-
-# clone the RIAB sources
-rm -rf riab-workspace && mkdir riab-workspace
-pushd riab-workspace
-git clone git@github.com:onosproject/sdran-in-a-box.git
-cd sdran-in-a-box
-
-kind delete cluster || kind create cluster
-sleep 30
-
-# initialize the system
-make clean
-sleep 30
 
 # override defaults for RIAB versions
 git checkout sdran-in-a-box*.yaml
@@ -73,7 +75,6 @@ sed -i -e "s#bess: docker.io/onosproject/riab-bess-upf:v1.0.0#bess: docker.io/on
 sed -i -e "s#pfcpiface: docker.io/onosproject/riab-pfcpiface:v1.0.0#pfcpiface: docker.io/onosproject/riab-pfcpiface:v1.0.0-onfvm-1#" sdran-in-a-box-values-master-stable.yaml
 
 # Install RIAB
-make clean-all
 make riab-oai-master-stable
 sleep 30
 
@@ -84,11 +85,11 @@ do
     if kubectl run cli-check-connections -n riab --rm -i --image onosproject/onos-cli:latest --restart Never --command /usr/local/bin/onos e2t list connections | grep --text G_NB
     then
         echo RAN in a Box smoke test passed!
-        make clean-all
+        make clean-all >/dev/null 2>/dev/null
         exit 0
     fi
     sleep 10
 done
 
-echo *** No G_NB connection found. Smoke test failed! ***
+echo '***' No G_NB connection found. Smoke test failed! '***'
 exit 1
