New format for connection ID

diff --git a/build/bin/smoke-onos-e2t b/build/bin/smoke-onos-e2t
--- a/build/bin/smoke-onos-e2t
+++ b/build/bin/smoke-onos-e2t
@@ -127,11 +127,12 @@ while read -r line ; do
         continue
     fi
     if [ $headers_found = "1" ]; then
-        IFS=':' read -a gid <<< ${tokens[0]}
-        # token 0 is the global ID, token 1 is the plnm ID
-        # global id should be plnm id followed by a colon followed by an identifier
-        if [ ${gid[0]} != ${tokens[1]} ]; then
+        if [[ ! $tokens[0] =~ ^[a-f0-9]*:[a-f0-9]*$ ]]; then
             echo "Global ID is incorrect. Failure!"
+            exit 1
+        fi
+        if [ $tokens[1] != "onf" ]; then
+            echo "plnm ID is incorrect. Failure!"
             exit 1
         fi
         if [[ ! ${tokens[2]} =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
