Adding plugin check to smoke test

diff --git a/build/bin/smoke-onos-config b/build/bin/smoke-onos-config
--- a/build/bin/smoke-onos-config
+++ b/build/bin/smoke-onos-config
@@ -15,6 +15,13 @@
 
 # This script is intended to be run from the onos-test directory as part of CI
 
+set -eu -o pipefail
+
+GREEN="\e[32m"
+RED="\e[31m"
+RESET="\e[0m"
+NAMESPACE=${NAMESPACE:-"micro-onos"}
+
 make_path () {
   target=$1
   path=$2
@@ -48,7 +55,7 @@ proxy="mirror.registry.opennetworking.org"
 setup_test_cluster
 
 # install onos-config
-helm install -n micro-onos $registry \
+helm install -n $NAMESPACE $registry \
      --set global.image.tag=latest \
      --set onos-config.image.tag=latest \
      --set onos-topo.image.tag=latest \
@@ -57,12 +64,22 @@ helm install -n micro-onos $registry \
      onos onos/onos-umbrella --wait
 
 # install the device simulator
-helm install -n micro-onos device-1 $registry onos/device-simulator --wait
+helm install -n $NAMESPACE device-1 $registry onos/device-simulator --wait
 
 # common gnmi_cli arguments
 common_args="-address onos-config:5150  -timeout 5s -en JSON -alsologtostderr \
              -insecure -client_crt /etc/ssl/certs/client1.crt -client_key /etc/ssl/certs/client1.key \
              -ca_crt /etc/ssl/certs/onfca.crt"
+
+# Check that plugin models have been loaded correctly
+# By default 3 model-plugins are loaded
+plugin_count=$($cli_command onos config get plugins --no-headers | grep Loaded | wc -l)
+if [[ "$plugin_count" == 3 ]]; then
+  echo -e "${GREEN}+++ Correct number of plugins loaded${RESET}"
+else
+  echo -e "${RED}*** Error: Wrong number of plugins loaded${RESET}"
+  exit 1
+fi
 
 # Create topo entries for the simulated device
 $cli_command onos topo create kind devicesim devicesim
@@ -80,9 +97,9 @@ bad_set=$($cli_command gnmi_cli -set $common_args -proto \
                 val: <string_val: 'Bad!Value'>>" 2>&1)
 if [[ "$bad_set" == *"code = InvalidArgument"* ]]
 then
-  echo "+++ Correct error returned for set of bad path"
+  echo -e "${GREEN}+++ Correct error returned for set of bad path${RESET}"
 else
-  echo "*** Error not returned for get of bad path"
+  echo -e "${RED}*** Error not returned for get of bad path${RESET}"
   exit 1
 fi
 
@@ -92,9 +109,9 @@ initial_set=$($cli_command gnmi_cli -set $common_args -proto \
                 val: <string_val: 'Europe/Paris'>>" 2>&1)
 if [[ "$initial_set" == *"op: UPDATE"* ]]
 then
-  echo "+++ Initial timezone set operation successful"
+  echo -e "${GREEN}+++ Initial timezone set operation successful${RESET}"
 else
-  echo "*** Error setting initial timezone value"
+  echo -e "${RED}*** Error setting initial timezone value${RESET}"
   exit 1
 fi
 
@@ -104,9 +121,9 @@ $cli_command gnmi_cli -get $common_args -proto "path: $tzpath" >$tmpfile
 timezone=$(extract_timezone)
 if [ "$timezone" == '"Europe/Paris"' ]
 then
-  echo "+++ Get of initial timezone setting is correct"
+  echo -e "${GREEN}+++ Get of initial timezone setting is correct${RESET}"
 else
-  echo "*** Get of initial timezone setting is incorrect"
+  echo -e "${RED}*** Get of initial timezone setting is incorrect${RESET}"
   exit 1
 fi
 
@@ -116,9 +133,9 @@ change_set=$($cli_command gnmi_cli -set $common_args -proto \
                 val: <string_val: 'Europe/Dublin'>>" 2>&1)
 if [[ "$change_set" == *"op: UPDATE"* ]]
 then
-  echo "+++ Change timezone set operation successful"
+  echo -e "${GREEN}+++ Change timezone set operation successful${RESET}"
 else
-  echo "*** Error changing timezone value"
+  echo -e "${RED}*** Error changing timezone value${RESET}"
   exit 1
 fi
 
@@ -128,9 +145,9 @@ $cli_command gnmi_cli -get $common_args -proto "path: $tzpath" >$tmpfile
 timezone=$(extract_timezone)
 if [ "$timezone" == '"Europe/Dublin"' ]
 then
-  echo "+++ Get of reset timezone setting is correct"
+  echo -e "${GREEN}+++ Get of reset timezone setting is correct${RESET}"
 else
-  echo "*** Get of reset timezone setting is incorrect"
+  echo -e "${RED}*** Get of reset timezone setting is incorrect${RESET}"
   exit 1
 fi
 
@@ -138,10 +155,10 @@ fi
 models_count=$($cli_command gnmi_cli -capabilities $common_args | grep supported_models | wc -l)
 if [ "$models_count" == '8' ]
 then
-  echo "+++ Models count from capabilities is correct"
+  echo -e "${GREEN}+++ Models count from capabilities is correct${RESET}"
 else
-  echo "*** Models count from capabilities is incorrect"
+  echo -e "${RED}*** Models count from capabilities is incorrect${RESET}"
   exit 1
 fi
 
-echo "=== onos-config smoke test completed successfully!"
+echo -e "${GREEN}=== onos-config smoke test completed successfully!${RESET}"
