New format for connection ID (#393)
* New format for connection ID

* Build and start onos-topo

* Fix the path to the onos-topo chart

* Need to bring up topo and ran-sim now

* remove bogus file

diff --git a/build/bin/smoke-onos-e2t b/build/bin/smoke-onos-e2t
--- a/build/bin/smoke-onos-e2t
+++ b/build/bin/smoke-onos-e2t
@@ -29,7 +29,7 @@ function waitForE2t {
 
 function waitForSim {
   while true; do
-    if kubectl -n micro-onos get pods -l type=e2-simulator | grep -q "1/1"; then
+    if kubectl -n micro-onos get pods -l type=sim | grep -q "1/1"; then
       break
     fi
     sleep 3
@@ -62,8 +62,9 @@ if [ "$#" -eq 2 ]; then
   # Pull the source repos
   pushd .. && git clone git@github.com:onosproject/onos-e2t.git && popd
   pushd .. && git clone git@github.com:onosproject/onos-e2sub.git && popd
-  pushd .. && git clone git@github.com:onosproject/e2-simulator.git && popd
+  pushd .. && git clone git@github.com:onosproject/ran-simulator.git && popd
   pushd .. && git clone git@github.com:onosproject/onos-cli.git && popd
+  pushd .. && git clone git@github.com:onosproject/onos-topo.git && popd
 
    # Download the onos helm charts
   pushd .. && git clone https://github.com/onosproject/onos-helm-charts.git && popd
@@ -84,7 +85,8 @@ kubectl create -f https://raw.githubusercontent.com/atomix/cache-storage-control
 # Build the images
 pushd ../onos-e2t && make kind && popd
 pushd ../onos-e2sub && make kind && popd
-pushd ../e2-simulator && make kind && popd
+pushd ../onos-topo && make kind && popd
+pushd ../ran-simulator && make kind && popd
 pushd ../onos-cli && make kind && popd
 
 pushd ..
@@ -95,10 +97,19 @@ helm repo add onos https://charts.onosproject.org
 helm repo add sdran --username "$repo_user" --password "$repo_password" https://sdrancharts.onosproject.org
 helm repo update
 
+# install Atomix
+kubectl create -f https://raw.githubusercontent.com/atomix/kubernetes-controller/master/deploy/atomix-controller.yaml
+kubectl create -f https://raw.githubusercontent.com/atomix/raft-storage-controller/master/deploy/raft-storage-controller.yaml
+kubectl create -f https://raw.githubusercontent.com/atomix/cache-storage-controller/master/deploy/cache-storage-controller.yaml
+
 # create a namespace for ONOS
 kubectl create namespace micro-onos
 
 # get the chart dependencies up to date
+
+# install onos-topo
+helm install -n micro-onos --set image.pullPolicy=Always --set image.tag=latest onos-topo onos/onos-topo
+
 cd sdran-helm-charts/sd-ran
 rm -rf charts Chart.lock
 helm dep build
@@ -108,8 +119,8 @@ helm dependency update sd-ran
 # install onos-e2t
 helm install -n micro-onos --set image.pullPolicy=Always --set image.tag=latest onos-e2t sdran/onos-e2t
 
-# Install the E2 simulator
-helm install -n micro-onos --set image.pullPolicy=Always --set image.tag=latest e2-simulator sdran/e2-simulator
+# Install the ran simulator
+helm install -n micro-onos --set image.pullPolicy=Always --set image.tag=latest ran-simulator sdran/ran-simulator
 
 # install onos-e2sub
 helm install -n micro-onos --set image.pullPolicy=Always --set image.tag=latest onos-e2sub sdran/onos-e2sub
@@ -132,18 +143,19 @@ while read -r line ; do
         continue
     fi
     if [ $headers_found = "1" ]; then
-        IFS=':' read -a gid <<< ${tokens[0]}
-        # token 0 is the global ID, token 1 is the plnm ID
-        # global id should be plnm id followed by a colon followed by an identifier
-        if [ ${gid[0]} != ${tokens[1]} ]; then
+        if [[ ! ${tokens[0]} =~ ^[a-f0-9]*:[a-f0-9]*$ ]]; then
             echo "Global ID is incorrect. Failure!"
+            exit 1
+        fi
+        if [ ${tokens[1]} != "onf" ]; then
+            echo "plnm ID is incorrect. Failure!"
             exit 1
         fi
         if [[ ! ${tokens[2]} =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
             echo "IP address is incorrect. Failure!"
             exit 1
         fi
-        if [ ${tokens[3]} != "36422" ]; then
+        if [[ ! ${tokens[3]} =~ ^[0-9]*$ ]]; then
             echo "Port is incorrect. Failure!"
             exit 1
         fi
