Adding plugin check to smoke test (#666)
* Adding plugin check to smoke test

* Remving colored output as it would pollute the Jenkins logs

diff --git a/build/bin/smoke-onos-config b/build/bin/smoke-onos-config
--- a/build/bin/smoke-onos-config
+++ b/build/bin/smoke-onos-config
@@ -15,6 +15,10 @@
 
 # This script is intended to be run from the onos-test directory as part of CI
 
+set -eu -o pipefail
+
+NAMESPACE=${NAMESPACE:-"micro-onos"}
+
 make_path () {
   target=$1
   path=$2
@@ -48,7 +52,7 @@ proxy="mirror.registry.opennetworking.org"
 setup_test_cluster
 
 # install onos-config
-helm install -n micro-onos $registry \
+helm install -n $NAMESPACE $registry \
      --set global.image.tag=latest \
      --set onos-config.image.tag=latest \
      --set onos-topo.image.tag=latest \
@@ -57,12 +61,22 @@ helm install -n micro-onos $registry \
      onos onos/onos-umbrella --wait
 
 # install the device simulator
-helm install -n micro-onos device-1 $registry onos/device-simulator --wait
+helm install -n $NAMESPACE device-1 $registry onos/device-simulator --wait
 
 # common gnmi_cli arguments
 common_args="-address onos-config:5150  -timeout 5s -en JSON -alsologtostderr \
              -insecure -client_crt /etc/ssl/certs/client1.crt -client_key /etc/ssl/certs/client1.key \
              -ca_crt /etc/ssl/certs/onfca.crt"
+
+# Check that plugin models have been loaded correctly
+# By default 3 model-plugins are loaded
+plugin_count=$($cli_command onos config get plugins --no-headers | grep Loaded | wc -l)
+if [[ "$plugin_count" == 3 ]]; then
+  echo "+++ Correct number of plugins loaded"
+else
+  echo "*** Error: Wrong number of plugins loaded"
+  exit 1
+fi
 
 # Create topo entries for the simulated device
 $cli_command onos topo create kind devicesim devicesim
